"use client";

import { useState } from "react";
import { Check, Download } from "@/components/ui/icons";
import { profileData } from "@/data/profile";
import { cn } from "@/lib/cn";

type DownloadCvButtonProps = {
  className?: string;
};

/** Builds a simple text CV from mock profile data for the visual prototype. */
export function DownloadCvButton({ className }: DownloadCvButtonProps) {
  const [done, setDone] = useState(false);
  const profile = profileData;

  const onDownload = () => {
    const lines = [
      profile.name,
      `${profile.title} · ${profile.year}`,
      `${profile.specialty} · ${profile.city}, ${profile.country}`,
      "",
      "Professional Summary",
      profile.summary.bio,
      "",
      "Career Goals",
      profile.summary.careerGoals,
      "",
      "Education",
      ...profile.education.map(
        (item) =>
          `- ${item.degree}, ${item.university} (${item.year}) · GPA ${item.gpa}`,
      ),
      "",
      "Clinical Experience",
      ...profile.clinicalExperience.flatMap((item) => [
        `- ${item.title} · ${item.hospital} · ${item.duration}`,
        ...item.responsibilities.map((line) => `  · ${line}`),
      ]),
      "",
      "Generated by MedJourney prototype",
    ];

    const blob = new Blob([lines.join("\n")], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${profile.name.replace(/\s+/g, "_")}_CV.txt`;
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);

    setDone(true);
    window.setTimeout(() => setDone(false), 1600);
  };

  return (
    <button
      type="button"
      onClick={onDownload}
      className={cn(
        "inline-flex min-h-11 items-center justify-center gap-2 rounded-[var(--mm-radius-lg)] border border-mm-border bg-mm-white px-4 text-[0.875rem] font-semibold text-mm-navy transition-[transform,box-shadow] duration-[var(--mm-duration)] hover:-translate-y-px hover:shadow-mm-sm",
        className,
      )}
    >
      {done ? (
        <Check size={16} strokeWidth={1.75} className="text-mm-teal" />
      ) : (
        <Download size={16} strokeWidth={1.75} />
      )}
      {done ? "CV downloaded" : "Download CV"}
    </button>
  );
}
